/* Write your PL/SQL query statement below */
WITH CTE AS(
    SELECT DEPARTMENTID, NAME, SALARY, 
    MAX(SALARY) OVER(PARTITION BY DEPARTMENTID) AS MAXI
    FROM EMPLOYEE
)
SELECT
D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY 
FROM CTE E JOIN DEPARTMENT D ON D.ID = E.DEPARTMENTID 
WHERE E.SALARY=E.MAXI;